"""
Django settings for adventure project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from adventure.settings.components.base import *
if os.environ.get('DUMMY_DB'):
    from adventure.settings.components.databases.dummy import *
else:
    from adventure.settings.components.databases.local_postgres import *
