language: python

cache: pip

python:
        - "3.7.3"
        - "3.7.5"
        - "3.8.0"

env:
        - DJANGO_ENV=ci

services:
        - postgresql

install:
        - pip install -r requirements/base.txt

before_script:
        - psql -c 'create database adventure;' -U postgres

script:
        - python manage.py makemigrations --dry-run --check
        - coverage run --source '.' manage.py test

after_script:
        - coverage xml
        - python-codacy-coverage -r coverage.xml
        - coveralls
