language: python

cache: pip





jobs:
  include:

    - stage: 'Tests'
      name: 'Unit Tests'
      python:
        - "3.6.9"
        - "3.7.5"
        - "3.8.0"
      env:
        - DJANGO_ENV=ci
      services:
        - postgresql
      install:
        - pip install -r requirements/ci.txt
      before_script:
        - psql -c 'create database adventure;' -U postgres
      script:
        - python manage.py makemigrations --dry-run --check
        - coverage run --source '.' manage.py test
      after_script:
        - coverage xml
        - python-codacy-coverage -r coverage.xml
        - coveralls

    - stage: 'Tests'
      name: 'Flake8'
      python:
        - '3.7.5'
      env:
        - DJANGO_ENV=ci
      install:
        - pip install flake8
      script:
        - flake8 .

    - stage: 'Tests'
      name: 'Pylint'
      python:
        - '3.7.5'
      env:
        - DJANGO_ENV=ci
        - DUMMY_DB=true
      install:
        - pip install pylint pylint-django
      script:
        - pylint adventure/ --rcfile=.pylintrc