language: python

cache: pip

jobs:
  include:

    - stage: 'Tests'
      name: 'Unit Tests'
      python:
        - "3.7.5"
      env:
        - DJANGO_ENV=ci
      services:
        - postgresql
      install:
        - pip install -r requirements/ci.txt
      script:
        - DUMMY_DB=true python manage.py makemigrations --dry-run --check
        - coverage run --source '.' manage.py test
      after_script:
        - coverage xml
        - python-codacy-coverage -r coverage.xml
        - coveralls

    - stage: 'Tests'
      name: 'Flake8'
      python:
        - '3.7.5'
      install:
        - pip install flake8
      script:
        - flake8 .

    - stage: 'Tests'
      name: 'Pylint'
      python:
        - '3.7.5'
      install:
        - pip install pylint pylint-django
      script:
        - python ci/run_pylint.py --target=adventure/ --rcfile=.pylintrc --score=8