language: python

python:
        - "3.7.3"

env:
        - DJANGO_ENV=ci

services:
        - postgresql

install:
        - pip install pipenv
        - pipenv sync

before_script:
        - psql -c 'create database adventure;' -U postgres

script:
        - pipenv run python manage.py makemigrations --dry-run --check
        - pipenv run python manage.py test
