language: python

python:
        - "3.7.3"

env:
        - DJANGO_ENV=ci

install:
        - 'pip install pipenv'
        - 'pipenv sync'
        - 'pipenv shell'

script:
        - 'python manage.py makemigrations --dry-run --check'
        - 'python manage.py test'
