language: python

python:
        - "3.7.3"

env:
        - DJANGO_ENV=ci

services:
        - postgresql

install:
        - 'pip install pipenv'
        - 'pipenv sync'

script:
        - 'pipenv run python manage.py makemigrations --dry-run --check'
        - 'pipenv run python manage.py test'
