# Generated by Django 2.2.1 on 2019-09-21 01:12

import adventure.magic.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('converted_mana_cost', models.IntegerField()),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(adventure.magic.models.Colors('Red'), 'Red'), (adventure.magic.models.Colors('Blue'), 'Blue'), (adventure.magic.models.Colors('Green'), 'Green'), (adventure.magic.models.Colors('White'), 'White'), (adventure.magic.models.Colors('Black'), 'Black')], max_length=8), size=None)),
                ('rarity', models.CharField(choices=[(adventure.magic.models.Rarity('Common'), 'Common'), (adventure.magic.models.Rarity('Uncommon'), 'Uncommon'), (adventure.magic.models.Rarity('Rare'), 'Rare'), (adventure.magic.models.Rarity('Mythic Rare'), 'Mythic Rare'), (adventure.magic.models.Rarity('Special'), 'Special'), (adventure.magic.models.Rarity('Basic Land'), 'Basic Land')], max_length=16)),
                ('commander_legal', models.BooleanField(default=False)),
                ('duel_legal', models.BooleanField(default=False)),
                ('legacy_legal', models.BooleanField(default=False)),
                ('modern_legal', models.BooleanField(default=False)),
                ('pauper_legal', models.BooleanField(default=False)),
                ('standard_legal', models.BooleanField(default=False)),
                ('vintage_legal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.Card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.Set')),
            ],
        ),
    ]
