# Generated by Django 2.2.4 on 2019-08-04 20:26

import django.contrib.postgres.fields
from django.db import migrations, models

import adventure.magic.models


class Migration(migrations.Migration):
    dependencies = [
        ('magic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[(adventure.magic.models.Colors('Red'), 'Red'),
                             (adventure.magic.models.Colors('Blue'), 'Blue'),
                             (adventure.magic.models.Colors('Green'), 'Green'),
                             (adventure.magic.models.Colors('White'), 'White'),
                             (
                             adventure.magic.models.Colors('Black'), 'Black')],
                    max_length=8), default=['White'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='commander_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='converted_mana_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='duel_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='legacy_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='modern_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='pauper_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(
                choices=[(adventure.magic.models.Rarity('Common'), 'Common'), (
                adventure.magic.models.Rarity('Uncommon'), 'Uncommon'),
                         (adventure.magic.models.Rarity('Rare'), 'Rare'), (
                         adventure.magic.models.Rarity('Mythic Rare'),
                         'Mythic Rare'),
                         (adventure.magic.models.Rarity('Special'), 'Special'),
                         (adventure.magic.models.Rarity('Basic Land'),
                          'Basic Land')], default='Common', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='standard_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='vintage_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='print',
            name='artist',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
